language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t cpal012/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cpal012/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "training-docker-react"
  env: "TrainingDockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-187792000890"
  bucket_path: "training-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY